
'=============================DECORATORS==================================
' We define 1 or more sprite decorators in stdlib
' Define our decorators that we know now - and can easily define new ones in future,
' with as many new parameters as we want, that we don't even know about yet.
'
'ref https://plantuml.com/preprocessing iuml
'---------------------------------------------------


@startuml(id=SPRITEDECORATOR_1)

!unquoted procedure $SpriteDecorator($MySprite, $alias, $description="", $label="", $technology="", $scale=1, $colour="red")

rectangle $alias as "
<<$alias>>
$label
<color:$colour><$MySprite*$scale></color>
//<size:12>[$technology]</size>//

  $description"
!endprocedure

@enduml



'add a new shape parameter
'---------------------------------------------------
@startuml(id=SPRITEDECORATOR_2)

!unquoted procedure $SpriteDecorator($MySprite, $alias, $description="", $label="", $technology="", $scale=1, $colour="green", $shape="node")

$shape $alias as "
<<$alias>>
$label
<color:$colour><$MySprite*$scale></color>
//<size:12>[$technology]</size>//

  $description"
!endprocedure

@enduml

'add a new shape parameter + a textsize parameter
'---------------------------------------------------
@startuml(id=SPRITEDECORATOR_3)

!unquoted procedure $SpriteDecorator($MySprite, $alias, $description="", $label="", $technology="", $scale=1, $colour="blue", $shape="cloud", $textsize="18")

$shape $alias as "
<<$alias>>
$label
<color:$colour><$MySprite*$scale></color>
//<size:$textsize>[$technology]</size>//

  $description "
!endprocedure

@enduml




'add the following features
'---------------------------------------------------
' "$shape $alias <<$alias>> as" is in form "shape alias <<stereo>> as" where skinparam can be specified for a stereo per https://plantuml.com/skinparam last example
' Show technology "[ ]" only if technology specified. Uses https://plantuml.com/preprocessing Conditions  
' Focus parameter: "hi", "lo" or anything else. Changes skinparams to highlight to lolight an icon. uses
'""== $label\n": "==" is creole syntax for "Large heading" https://plantuml.com/creole

@startuml(id=SPRITEDECORATOR_4)


!unquoted procedure $SpriteDecorator($MySprite, $alias, $description="", $label="", $technology="", $scale=1, $colour="blue", $shape="rectangle", $textsize="18", $focus="" )

!if ($focus == "hi")
    skinparam rectangle {
        backgroundColor<<$alias>> yellow
        borderColor<<$alias>> yellow
        shadowing<<$alias>> true
        BorderThickness<<$alias>> 20
    }
!endif

!if  ($focus == "lo")
    skinparam rectangle {
        backgroundColor<<$alias>> gainsboro
        borderColor<<$alias>> gainsboro
        shadowing<<$alias>> false
        
    }
!endif


!if ($technology == "")
    $shape $alias <<$alias>> as "
    == $label\n
    <color:$colour><$MySprite*$scale></color>

    $description "
!else 
    $shape $alias <<$alias>> as "
    == $label\n
    <color:$colour><$MySprite*$scale></color>
    //<size:$textsize>[$technology]</size>//

    $description "
!endif

!endprocedure

@enduml